version: '2'
services:
    nginx: 
        build: ./docker/nginx
        ports:
            - 80:80
        depends_on:
            - api
    api:
        build: .
        ports: 
            - 8888:8888
        depends_on:
            - mongodb
            - redis
            - mysql
        environment:
            - LOG_LEVEL=debug
            - LOG_FILE_NAME=api.log
            - LOG_TO_FILE=false
            - ENABLE_NEW_RELIC=false
            - NEW_RELIC_LICENSE_KEY=key
            - NEW_RELIC_PROXY_URL=http://newrelicproxy.com
            - MONGO_URL=mongodb 
            - MONGO_PORT=27017 
            - MONGO_TIMEOUT=60
            - MONGO_DATABASE_NAME=api
            - REDIS_URL=redis
            - MYSQL_URL=mysql
            - MYSQL_USER=golang
            - MYSQL_PASSWORD=golangUserPassword
            - MYSQL_DATABASE=example
    mongodb:
        image: mongo:3.2.10
    mysql:
        image: mysql/mysql-server:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=golang
            - MYSQL_PASSWORD=golangUserPassword
            - MYSQL_DATABASE=example
        ports:
            - 3306:3306
    redis:
        image: redis:3
    