version: '2'
services:
    nginx: 
        build: ./docker/nginx
        ports:
            - 80:80
        depends_on:
            - api
    api:
        build: .
        ports: 
            - 8888:8888
        depends_on:
            - mongodb
            - redis
        environment:
            - LOG_LEVEL=debug
            - LOG_FILE_NAME=api.log
            - LOG_TO_FILE=false
            - MONGO_URL=mongodb 
            - MONGO_PORT=27017 
            - MONGO_TIMEOUT=60
            - MONGO_DATABASE_NAME=api
            - REDIS_URL=redis
    mongodb:
        image: mongo:3.2.10
    redis:
        image: redis:3
    