version: '2'
services:
    nginx: 
        build: ./docker/nginx
        ports:
            - 80:80
        depends_on:
            - api
    api:
        build: .
        ports: 
            - 8888:8888
        depends_on:
            - mongodb
            - redis
            - mysql
        environment:
            - LOG_LEVEL=debug
            - LOG_FILE_NAME=api.log
            - LOG_TO_FILE=false
            - ENABLE_NEW_RELIC=false
            - NEW_RELIC_LICENSE_KEY=key
            - NEW_RELIC_PROXY_URL=http://newrelicproxy.com
            - MONGO_URL=mongodb 
            - MONGO_PORT=27017 
            - MONGO_TIMEOUT=60
            - MONGO_DATABASE_NAME=api
            - REDIS_URL=redis

            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_DATABASE_NAME=skeleton_database
            - MYSQL_DATABASE_USERNAME=golang
            - MYSQL_DATABASE_PASSWORD=golang
    mongodb:
        image: mongo:3.2.10
        volumes:
            - /tmp/db/mongodb:/var/lib/db
    mysql:
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=my-secret-pw
            - MYSQL_USER=golang
            - MYSQL_PASSWORD=golang
            - MYSQL_DATABASE=skeleton_database
        volumes:
            - /tmp/db/mysql:/var/lib/mysql
    redis:
        image: redis:3
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
        ports: 
            - 9090:9090